name: Build and Deploy Spigot Plugin

on:
  push:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Clean with Maven
      run: mvn clean

    - name: Download Maven Dependencies
      run: mvn dependency:resolve

    - name: Test with Maven
      run: mvn test

    - name: Package with Maven
      run: mvn package